# Generated by Django 2.2.6 on 2020-04-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avgDailyIncomeInUSD', models.FloatField()),
                ('avgAge', models.FloatField()),
                ('avgDailyIncomePopulation', models.FloatField()),
                ('periodType', models.CharField(max_length=10)),
                ('timeToElapse', models.IntegerField()),
                ('reportedCases', models.IntegerField()),
                ('population', models.IntegerField()),
                ('totalHospitalBeds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlyInfected', models.IntegerField()),
                ('infectionsByRequestedTime', models.IntegerField()),
                ('severeCasesByRequestedTime', models.FloatField()),
                ('hospitalBedsByRequestedTime', models.FloatField()),
                ('casesForICUByRequestedTime', models.FloatField()),
                ('casesForVentilatorsByRequestedTime', models.FloatField()),
                ('dollarsInFlight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SevereImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlyInfected', models.IntegerField()),
                ('infectionsByRequestedTime', models.IntegerField()),
                ('severeCasesByRequestedTime', models.FloatField()),
                ('hospitalBedsByRequestedTime', models.FloatField()),
                ('casesForICUByRequestedTime', models.FloatField()),
                ('casesForVentilatorsByRequestedTime', models.FloatField()),
                ('dollarsInFlight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimator.Impact')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimator.Estimator')),
                ('severeImpact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimator.SevereImpact')),
            ],
        ),
    ]
