# Generated by Django 2.2.6 on 2020-04-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='output',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='output',
            name='severeImpact',
        ),
        migrations.DeleteModel(
            name='Impact',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='SevereImpact',
        ),
    ]
